name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Linux Binary
        run: |
          pyinstaller --onefile --name syswhisperer --target-arch x86_64 main.py

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: dist/syswhisperer

  build-windows:
    runs-on: windows-latest  # Используем Windows для сборки
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'  # Явно указываем 64-битную версию

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows Binary
        run: |
          pyinstaller --onefile --name syswhisperer.exe --target-arch x86_64 main.py

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: dist/syswhisperer.exe

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: dist

      - name: Download Windows Binary
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/syswhisperer
            dist/syswhisperer.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}